version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choose an appropriate Python version

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python -m unittest discover

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

