version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.0
  aws-ecs: circleci/aws-ecs@04.0.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "python-webapp"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: "python-webapp-service"
          cluster: "python-webapp-cluster"
          container-image-name-updates: "container=python-webapp-service,tag=${CIRCLE_SHA1}"
